namespace InventoryManagementSystem
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.MinimizeAppButton = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.MainPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.CloseButton = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.ProductsButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CustomersButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.UsersButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.OrdersButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SaleLedgerButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SaleButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DashboardButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 20;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Black;
            this.bunifuPanel1.BorderRadius = 10;
            this.bunifuPanel1.BorderThickness = 2;
            this.bunifuPanel1.Controls.Add(this.MinimizeAppButton);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.MainPanel);
            this.bunifuPanel1.Controls.Add(this.CloseButton);
            this.bunifuPanel1.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1155, 800);
            this.bunifuPanel1.TabIndex = 4;
            // 
            // MinimizeAppButton
            // 
            this.MinimizeAppButton.ActiveImage = global::InventoryManagementSystem.Properties.Resources.Minimize;
            this.MinimizeAppButton.AllowAnimations = true;
            this.MinimizeAppButton.AllowBuffering = false;
            this.MinimizeAppButton.AllowToggling = false;
            this.MinimizeAppButton.AllowZooming = true;
            this.MinimizeAppButton.AllowZoomingOnFocus = false;
            this.MinimizeAppButton.BackColor = System.Drawing.Color.Transparent;
            this.MinimizeAppButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MinimizeAppButton.ErrorImage = ((System.Drawing.Image)(resources.GetObject("MinimizeAppButton.ErrorImage")));
            this.MinimizeAppButton.FadeWhenInactive = false;
            this.MinimizeAppButton.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.MinimizeAppButton.Image = global::InventoryManagementSystem.Properties.Resources.Minimize;
            this.MinimizeAppButton.ImageActive = global::InventoryManagementSystem.Properties.Resources.Minimize;
            this.MinimizeAppButton.ImageLocation = null;
            this.MinimizeAppButton.ImageMargin = 0;
            this.MinimizeAppButton.ImageSize = new System.Drawing.Size(29, 29);
            this.MinimizeAppButton.ImageZoomSize = new System.Drawing.Size(30, 30);
            this.MinimizeAppButton.InitialImage = ((System.Drawing.Image)(resources.GetObject("MinimizeAppButton.InitialImage")));
            this.MinimizeAppButton.Location = new System.Drawing.Point(1080, 7);
            this.MinimizeAppButton.Name = "MinimizeAppButton";
            this.MinimizeAppButton.Rotation = 0;
            this.MinimizeAppButton.ShowActiveImage = true;
            this.MinimizeAppButton.ShowCursorChanges = true;
            this.MinimizeAppButton.ShowImageBorders = true;
            this.MinimizeAppButton.ShowSizeMarkers = false;
            this.MinimizeAppButton.Size = new System.Drawing.Size(30, 30);
            this.MinimizeAppButton.TabIndex = 3;
            this.MinimizeAppButton.ToolTipText = "";
            this.MinimizeAppButton.WaitOnLoad = false;
            this.MinimizeAppButton.Zoom = 0;
            this.MinimizeAppButton.ZoomSpeed = 10;
            this.MinimizeAppButton.Click += new System.EventHandler(this.MinimizeAppButton_Click);
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Bebas", 20.25F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel3.Location = new System.Drawing.Point(244, 0);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(314, 33);
            this.bunifuLabel3.TabIndex = 1;
            this.bunifuLabel3.Text = "Al-Makkah Tile and Marble Shop";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // MainPanel
            // 
            this.MainPanel.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(245)))), ((int)(((byte)(224)))));
            this.MainPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MainPanel.BackgroundImage")));
            this.MainPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.MainPanel.BorderColor = System.Drawing.Color.Transparent;
            this.MainPanel.BorderRadius = 15;
            this.MainPanel.BorderThickness = 1;
            this.MainPanel.Location = new System.Drawing.Point(241, 39);
            this.MainPanel.Name = "MainPanel";
            this.MainPanel.ShowBorders = true;
            this.MainPanel.Size = new System.Drawing.Size(900, 750);
            this.MainPanel.TabIndex = 2;
            // 
            // CloseButton
            // 
            this.CloseButton.ActiveImage = global::InventoryManagementSystem.Properties.Resources.Close;
            this.CloseButton.AllowAnimations = true;
            this.CloseButton.AllowBuffering = false;
            this.CloseButton.AllowToggling = false;
            this.CloseButton.AllowZooming = true;
            this.CloseButton.AllowZoomingOnFocus = false;
            this.CloseButton.BackColor = System.Drawing.Color.Transparent;
            this.CloseButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CloseButton.ErrorImage = ((System.Drawing.Image)(resources.GetObject("CloseButton.ErrorImage")));
            this.CloseButton.FadeWhenInactive = false;
            this.CloseButton.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.CloseButton.Image = global::InventoryManagementSystem.Properties.Resources.Close;
            this.CloseButton.ImageActive = global::InventoryManagementSystem.Properties.Resources.Close;
            this.CloseButton.ImageLocation = null;
            this.CloseButton.ImageMargin = 0;
            this.CloseButton.ImageSize = new System.Drawing.Size(29, 29);
            this.CloseButton.ImageZoomSize = new System.Drawing.Size(30, 30);
            this.CloseButton.InitialImage = ((System.Drawing.Image)(resources.GetObject("CloseButton.InitialImage")));
            this.CloseButton.Location = new System.Drawing.Point(1111, 7);
            this.CloseButton.Name = "CloseButton";
            this.CloseButton.Rotation = 0;
            this.CloseButton.ShowActiveImage = true;
            this.CloseButton.ShowCursorChanges = true;
            this.CloseButton.ShowImageBorders = true;
            this.CloseButton.ShowSizeMarkers = false;
            this.CloseButton.Size = new System.Drawing.Size(30, 30);
            this.CloseButton.TabIndex = 3;
            this.CloseButton.ToolTipText = "";
            this.CloseButton.WaitOnLoad = false;
            this.CloseButton.Zoom = 0;
            this.CloseButton.ZoomSpeed = 10;
            this.CloseButton.Click += new System.EventHandler(this.CloseButton_Click);
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.bunifuShadowPanel2.BorderRadius = 10;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel2.Controls.Add(this.ProductsButton);
            this.bunifuShadowPanel2.Controls.Add(this.CustomersButton);
            this.bunifuShadowPanel2.Controls.Add(this.UsersButton);
            this.bunifuShadowPanel2.Controls.Add(this.OrdersButton);
            this.bunifuShadowPanel2.Controls.Add(this.SaleLedgerButton);
            this.bunifuShadowPanel2.Controls.Add(this.SaleButton);
            this.bunifuShadowPanel2.Controls.Add(this.DashboardButton);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(10, 39);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 0;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(225, 748);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 1;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::InventoryManagementSystem.Properties.Resources.Inventory1;
            this.pictureBox1.Location = new System.Drawing.Point(46, 114);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(124, 134);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 2;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Bebas", 20.25F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(58, 17);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(103, 33);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "Al-Makkah";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Bebas", 18F);
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 49);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(198, 59);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Inventory Management\r\nSystem";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ProductsButton
            // 
            this.ProductsButton.AllowAnimations = true;
            this.ProductsButton.AllowMouseEffects = true;
            this.ProductsButton.AllowToggling = false;
            this.ProductsButton.AnimationSpeed = 200;
            this.ProductsButton.AutoGenerateColors = false;
            this.ProductsButton.AutoRoundBorders = false;
            this.ProductsButton.AutoSizeLeftIcon = true;
            this.ProductsButton.AutoSizeRightIcon = true;
            this.ProductsButton.BackColor = System.Drawing.Color.Transparent;
            this.ProductsButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ProductsButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProductsButton.BackgroundImage")));
            this.ProductsButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.ProductsButton.ButtonText = "Products";
            this.ProductsButton.ButtonTextMarginLeft = 0;
            this.ProductsButton.ColorContrastOnClick = 45;
            this.ProductsButton.ColorContrastOnHover = 45;
            this.ProductsButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ProductsButton.CustomizableEdges = borderEdges1;
            this.ProductsButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ProductsButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProductsButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductsButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProductsButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ProductsButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ProductsButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.ProductsButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ProductsButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ProductsButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ProductsButton.IconMarginLeft = 11;
            this.ProductsButton.IconPadding = 10;
            this.ProductsButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ProductsButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ProductsButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ProductsButton.IconSize = 25;
            this.ProductsButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.ProductsButton.IdleBorderRadius = 15;
            this.ProductsButton.IdleBorderThickness = 1;
            this.ProductsButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ProductsButton.IdleIconLeftImage = null;
            this.ProductsButton.IdleIconRightImage = null;
            this.ProductsButton.IndicateFocus = true;
            this.ProductsButton.Location = new System.Drawing.Point(21, 341);
            this.ProductsButton.Name = "ProductsButton";
            this.ProductsButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProductsButton.OnDisabledState.BorderRadius = 15;
            this.ProductsButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProductsButton.OnDisabledState.BorderThickness = 1;
            this.ProductsButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductsButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProductsButton.OnDisabledState.IconLeftImage = null;
            this.ProductsButton.OnDisabledState.IconRightImage = null;
            this.ProductsButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.ProductsButton.onHoverState.BorderRadius = 15;
            this.ProductsButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.ProductsButton.onHoverState.BorderThickness = 1;
            this.ProductsButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.ProductsButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.ProductsButton.onHoverState.IconLeftImage = null;
            this.ProductsButton.onHoverState.IconRightImage = null;
            this.ProductsButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.ProductsButton.OnIdleState.BorderRadius = 15;
            this.ProductsButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.ProductsButton.OnIdleState.BorderThickness = 1;
            this.ProductsButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ProductsButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.ProductsButton.OnIdleState.IconLeftImage = null;
            this.ProductsButton.OnIdleState.IconRightImage = null;
            this.ProductsButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProductsButton.OnPressedState.BorderRadius = 15;
            this.ProductsButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProductsButton.OnPressedState.BorderThickness = 1;
            this.ProductsButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProductsButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ProductsButton.OnPressedState.IconLeftImage = null;
            this.ProductsButton.OnPressedState.IconRightImage = null;
            this.ProductsButton.Size = new System.Drawing.Size(182, 39);
            this.ProductsButton.TabIndex = 0;
            this.ProductsButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ProductsButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ProductsButton.TextMarginLeft = 0;
            this.ProductsButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ProductsButton.UseDefaultRadiusAndThickness = true;
            this.ProductsButton.Click += new System.EventHandler(this.ProductsButton_Click);
            // 
            // CustomersButton
            // 
            this.CustomersButton.AllowAnimations = true;
            this.CustomersButton.AllowMouseEffects = true;
            this.CustomersButton.AllowToggling = false;
            this.CustomersButton.AnimationSpeed = 200;
            this.CustomersButton.AutoGenerateColors = false;
            this.CustomersButton.AutoRoundBorders = false;
            this.CustomersButton.AutoSizeLeftIcon = true;
            this.CustomersButton.AutoSizeRightIcon = true;
            this.CustomersButton.BackColor = System.Drawing.Color.Transparent;
            this.CustomersButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.CustomersButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CustomersButton.BackgroundImage")));
            this.CustomersButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.CustomersButton.ButtonText = "Customers";
            this.CustomersButton.ButtonTextMarginLeft = 0;
            this.CustomersButton.ColorContrastOnClick = 45;
            this.CustomersButton.ColorContrastOnHover = 45;
            this.CustomersButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.CustomersButton.CustomizableEdges = borderEdges2;
            this.CustomersButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CustomersButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CustomersButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CustomersButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CustomersButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CustomersButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CustomersButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.CustomersButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CustomersButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CustomersButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CustomersButton.IconMarginLeft = 11;
            this.CustomersButton.IconPadding = 10;
            this.CustomersButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CustomersButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CustomersButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CustomersButton.IconSize = 25;
            this.CustomersButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.CustomersButton.IdleBorderRadius = 15;
            this.CustomersButton.IdleBorderThickness = 1;
            this.CustomersButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.CustomersButton.IdleIconLeftImage = null;
            this.CustomersButton.IdleIconRightImage = null;
            this.CustomersButton.IndicateFocus = true;
            this.CustomersButton.Location = new System.Drawing.Point(21, 474);
            this.CustomersButton.Name = "CustomersButton";
            this.CustomersButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CustomersButton.OnDisabledState.BorderRadius = 15;
            this.CustomersButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CustomersButton.OnDisabledState.BorderThickness = 1;
            this.CustomersButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CustomersButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CustomersButton.OnDisabledState.IconLeftImage = null;
            this.CustomersButton.OnDisabledState.IconRightImage = null;
            this.CustomersButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.CustomersButton.onHoverState.BorderRadius = 15;
            this.CustomersButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.CustomersButton.onHoverState.BorderThickness = 1;
            this.CustomersButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.CustomersButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.CustomersButton.onHoverState.IconLeftImage = null;
            this.CustomersButton.onHoverState.IconRightImage = null;
            this.CustomersButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.CustomersButton.OnIdleState.BorderRadius = 15;
            this.CustomersButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.CustomersButton.OnIdleState.BorderThickness = 1;
            this.CustomersButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.CustomersButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.CustomersButton.OnIdleState.IconLeftImage = null;
            this.CustomersButton.OnIdleState.IconRightImage = null;
            this.CustomersButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CustomersButton.OnPressedState.BorderRadius = 15;
            this.CustomersButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CustomersButton.OnPressedState.BorderThickness = 1;
            this.CustomersButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CustomersButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.CustomersButton.OnPressedState.IconLeftImage = null;
            this.CustomersButton.OnPressedState.IconRightImage = null;
            this.CustomersButton.Size = new System.Drawing.Size(182, 39);
            this.CustomersButton.TabIndex = 0;
            this.CustomersButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CustomersButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CustomersButton.TextMarginLeft = 0;
            this.CustomersButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.CustomersButton.UseDefaultRadiusAndThickness = true;
            this.CustomersButton.Click += new System.EventHandler(this.CustomersButton_Click);
            // 
            // UsersButton
            // 
            this.UsersButton.AllowAnimations = true;
            this.UsersButton.AllowMouseEffects = true;
            this.UsersButton.AllowToggling = false;
            this.UsersButton.AnimationSpeed = 200;
            this.UsersButton.AutoGenerateColors = false;
            this.UsersButton.AutoRoundBorders = false;
            this.UsersButton.AutoSizeLeftIcon = true;
            this.UsersButton.AutoSizeRightIcon = true;
            this.UsersButton.BackColor = System.Drawing.Color.Transparent;
            this.UsersButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.UsersButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UsersButton.BackgroundImage")));
            this.UsersButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.UsersButton.ButtonText = "Users";
            this.UsersButton.ButtonTextMarginLeft = 0;
            this.UsersButton.ColorContrastOnClick = 45;
            this.UsersButton.ColorContrastOnHover = 45;
            this.UsersButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.UsersButton.CustomizableEdges = borderEdges3;
            this.UsersButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UsersButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UsersButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsersButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UsersButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UsersButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UsersButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.UsersButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UsersButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UsersButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UsersButton.IconMarginLeft = 11;
            this.UsersButton.IconPadding = 10;
            this.UsersButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UsersButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UsersButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UsersButton.IconSize = 25;
            this.UsersButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.UsersButton.IdleBorderRadius = 15;
            this.UsersButton.IdleBorderThickness = 1;
            this.UsersButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.UsersButton.IdleIconLeftImage = null;
            this.UsersButton.IdleIconRightImage = null;
            this.UsersButton.IndicateFocus = true;
            this.UsersButton.Location = new System.Drawing.Point(21, 675);
            this.UsersButton.Name = "UsersButton";
            this.UsersButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UsersButton.OnDisabledState.BorderRadius = 15;
            this.UsersButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersButton.OnDisabledState.BorderThickness = 1;
            this.UsersButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsersButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UsersButton.OnDisabledState.IconLeftImage = null;
            this.UsersButton.OnDisabledState.IconRightImage = null;
            this.UsersButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.UsersButton.onHoverState.BorderRadius = 15;
            this.UsersButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.UsersButton.onHoverState.BorderThickness = 1;
            this.UsersButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.UsersButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.UsersButton.onHoverState.IconLeftImage = null;
            this.UsersButton.onHoverState.IconRightImage = null;
            this.UsersButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.UsersButton.OnIdleState.BorderRadius = 15;
            this.UsersButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.UsersButton.OnIdleState.BorderThickness = 1;
            this.UsersButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.UsersButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.UsersButton.OnIdleState.IconLeftImage = null;
            this.UsersButton.OnIdleState.IconRightImage = null;
            this.UsersButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UsersButton.OnPressedState.BorderRadius = 15;
            this.UsersButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersButton.OnPressedState.BorderThickness = 1;
            this.UsersButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UsersButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.UsersButton.OnPressedState.IconLeftImage = null;
            this.UsersButton.OnPressedState.IconRightImage = null;
            this.UsersButton.Size = new System.Drawing.Size(182, 39);
            this.UsersButton.TabIndex = 0;
            this.UsersButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UsersButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UsersButton.TextMarginLeft = 0;
            this.UsersButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.UsersButton.UseDefaultRadiusAndThickness = true;
            this.UsersButton.Click += new System.EventHandler(this.UsersButton_Click);
            // 
            // OrdersButton
            // 
            this.OrdersButton.AllowAnimations = true;
            this.OrdersButton.AllowMouseEffects = true;
            this.OrdersButton.AllowToggling = false;
            this.OrdersButton.AnimationSpeed = 200;
            this.OrdersButton.AutoGenerateColors = false;
            this.OrdersButton.AutoRoundBorders = false;
            this.OrdersButton.AutoSizeLeftIcon = true;
            this.OrdersButton.AutoSizeRightIcon = true;
            this.OrdersButton.BackColor = System.Drawing.Color.Transparent;
            this.OrdersButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.OrdersButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("OrdersButton.BackgroundImage")));
            this.OrdersButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.OrdersButton.ButtonText = "Orders";
            this.OrdersButton.ButtonTextMarginLeft = 0;
            this.OrdersButton.ColorContrastOnClick = 45;
            this.OrdersButton.ColorContrastOnHover = 45;
            this.OrdersButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.OrdersButton.CustomizableEdges = borderEdges4;
            this.OrdersButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.OrdersButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.OrdersButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.OrdersButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.OrdersButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.OrdersButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OrdersButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.OrdersButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.OrdersButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.OrdersButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.OrdersButton.IconMarginLeft = 11;
            this.OrdersButton.IconPadding = 10;
            this.OrdersButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.OrdersButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.OrdersButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.OrdersButton.IconSize = 25;
            this.OrdersButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.OrdersButton.IdleBorderRadius = 15;
            this.OrdersButton.IdleBorderThickness = 1;
            this.OrdersButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.OrdersButton.IdleIconLeftImage = null;
            this.OrdersButton.IdleIconRightImage = null;
            this.OrdersButton.IndicateFocus = true;
            this.OrdersButton.Location = new System.Drawing.Point(21, 608);
            this.OrdersButton.Name = "OrdersButton";
            this.OrdersButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.OrdersButton.OnDisabledState.BorderRadius = 15;
            this.OrdersButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.OrdersButton.OnDisabledState.BorderThickness = 1;
            this.OrdersButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.OrdersButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.OrdersButton.OnDisabledState.IconLeftImage = null;
            this.OrdersButton.OnDisabledState.IconRightImage = null;
            this.OrdersButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.OrdersButton.onHoverState.BorderRadius = 15;
            this.OrdersButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.OrdersButton.onHoverState.BorderThickness = 1;
            this.OrdersButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.OrdersButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.OrdersButton.onHoverState.IconLeftImage = null;
            this.OrdersButton.onHoverState.IconRightImage = null;
            this.OrdersButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.OrdersButton.OnIdleState.BorderRadius = 15;
            this.OrdersButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.OrdersButton.OnIdleState.BorderThickness = 1;
            this.OrdersButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.OrdersButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.OrdersButton.OnIdleState.IconLeftImage = null;
            this.OrdersButton.OnIdleState.IconRightImage = null;
            this.OrdersButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.OrdersButton.OnPressedState.BorderRadius = 15;
            this.OrdersButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.OrdersButton.OnPressedState.BorderThickness = 1;
            this.OrdersButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.OrdersButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.OrdersButton.OnPressedState.IconLeftImage = null;
            this.OrdersButton.OnPressedState.IconRightImage = null;
            this.OrdersButton.Size = new System.Drawing.Size(182, 39);
            this.OrdersButton.TabIndex = 0;
            this.OrdersButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.OrdersButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.OrdersButton.TextMarginLeft = 0;
            this.OrdersButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.OrdersButton.UseDefaultRadiusAndThickness = true;
            this.OrdersButton.Click += new System.EventHandler(this.OrdersButton_Click);
            // 
            // SaleLedgerButton
            // 
            this.SaleLedgerButton.AllowAnimations = true;
            this.SaleLedgerButton.AllowMouseEffects = true;
            this.SaleLedgerButton.AllowToggling = false;
            this.SaleLedgerButton.AnimationSpeed = 200;
            this.SaleLedgerButton.AutoGenerateColors = false;
            this.SaleLedgerButton.AutoRoundBorders = false;
            this.SaleLedgerButton.AutoSizeLeftIcon = true;
            this.SaleLedgerButton.AutoSizeRightIcon = true;
            this.SaleLedgerButton.BackColor = System.Drawing.Color.Transparent;
            this.SaleLedgerButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.SaleLedgerButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SaleLedgerButton.BackgroundImage")));
            this.SaleLedgerButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.SaleLedgerButton.ButtonText = "Sale Ledger";
            this.SaleLedgerButton.ButtonTextMarginLeft = 0;
            this.SaleLedgerButton.ColorContrastOnClick = 45;
            this.SaleLedgerButton.ColorContrastOnHover = 45;
            this.SaleLedgerButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.SaleLedgerButton.CustomizableEdges = borderEdges5;
            this.SaleLedgerButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SaleLedgerButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaleLedgerButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaleLedgerButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaleLedgerButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SaleLedgerButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SaleLedgerButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.SaleLedgerButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SaleLedgerButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SaleLedgerButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SaleLedgerButton.IconMarginLeft = 11;
            this.SaleLedgerButton.IconPadding = 10;
            this.SaleLedgerButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SaleLedgerButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SaleLedgerButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SaleLedgerButton.IconSize = 25;
            this.SaleLedgerButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.SaleLedgerButton.IdleBorderRadius = 15;
            this.SaleLedgerButton.IdleBorderThickness = 1;
            this.SaleLedgerButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.SaleLedgerButton.IdleIconLeftImage = null;
            this.SaleLedgerButton.IdleIconRightImage = null;
            this.SaleLedgerButton.IndicateFocus = true;
            this.SaleLedgerButton.Location = new System.Drawing.Point(21, 541);
            this.SaleLedgerButton.Name = "SaleLedgerButton";
            this.SaleLedgerButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaleLedgerButton.OnDisabledState.BorderRadius = 15;
            this.SaleLedgerButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaleLedgerButton.OnDisabledState.BorderThickness = 1;
            this.SaleLedgerButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaleLedgerButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaleLedgerButton.OnDisabledState.IconLeftImage = null;
            this.SaleLedgerButton.OnDisabledState.IconRightImage = null;
            this.SaleLedgerButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.SaleLedgerButton.onHoverState.BorderRadius = 15;
            this.SaleLedgerButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.SaleLedgerButton.onHoverState.BorderThickness = 1;
            this.SaleLedgerButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.SaleLedgerButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.SaleLedgerButton.onHoverState.IconLeftImage = null;
            this.SaleLedgerButton.onHoverState.IconRightImage = null;
            this.SaleLedgerButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.SaleLedgerButton.OnIdleState.BorderRadius = 15;
            this.SaleLedgerButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.SaleLedgerButton.OnIdleState.BorderThickness = 1;
            this.SaleLedgerButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.SaleLedgerButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.SaleLedgerButton.OnIdleState.IconLeftImage = null;
            this.SaleLedgerButton.OnIdleState.IconRightImage = null;
            this.SaleLedgerButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaleLedgerButton.OnPressedState.BorderRadius = 15;
            this.SaleLedgerButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaleLedgerButton.OnPressedState.BorderThickness = 1;
            this.SaleLedgerButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaleLedgerButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SaleLedgerButton.OnPressedState.IconLeftImage = null;
            this.SaleLedgerButton.OnPressedState.IconRightImage = null;
            this.SaleLedgerButton.Size = new System.Drawing.Size(182, 39);
            this.SaleLedgerButton.TabIndex = 0;
            this.SaleLedgerButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SaleLedgerButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SaleLedgerButton.TextMarginLeft = 0;
            this.SaleLedgerButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.SaleLedgerButton.UseDefaultRadiusAndThickness = true;
            this.SaleLedgerButton.Click += new System.EventHandler(this.SaleLedgerButton_Click);
            // 
            // SaleButton
            // 
            this.SaleButton.AllowAnimations = true;
            this.SaleButton.AllowMouseEffects = true;
            this.SaleButton.AllowToggling = false;
            this.SaleButton.AnimationSpeed = 200;
            this.SaleButton.AutoGenerateColors = false;
            this.SaleButton.AutoRoundBorders = false;
            this.SaleButton.AutoSizeLeftIcon = true;
            this.SaleButton.AutoSizeRightIcon = true;
            this.SaleButton.BackColor = System.Drawing.Color.Transparent;
            this.SaleButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.SaleButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SaleButton.BackgroundImage")));
            this.SaleButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.SaleButton.ButtonText = "Sale";
            this.SaleButton.ButtonTextMarginLeft = 0;
            this.SaleButton.ColorContrastOnClick = 45;
            this.SaleButton.ColorContrastOnHover = 45;
            this.SaleButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.SaleButton.CustomizableEdges = borderEdges6;
            this.SaleButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SaleButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaleButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaleButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaleButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SaleButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SaleButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.SaleButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SaleButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SaleButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SaleButton.IconMarginLeft = 11;
            this.SaleButton.IconPadding = 10;
            this.SaleButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SaleButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SaleButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SaleButton.IconSize = 25;
            this.SaleButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.SaleButton.IdleBorderRadius = 15;
            this.SaleButton.IdleBorderThickness = 1;
            this.SaleButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.SaleButton.IdleIconLeftImage = null;
            this.SaleButton.IdleIconRightImage = null;
            this.SaleButton.IndicateFocus = true;
            this.SaleButton.Location = new System.Drawing.Point(21, 407);
            this.SaleButton.Name = "SaleButton";
            this.SaleButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaleButton.OnDisabledState.BorderRadius = 15;
            this.SaleButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaleButton.OnDisabledState.BorderThickness = 1;
            this.SaleButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaleButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaleButton.OnDisabledState.IconLeftImage = null;
            this.SaleButton.OnDisabledState.IconRightImage = null;
            this.SaleButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.SaleButton.onHoverState.BorderRadius = 15;
            this.SaleButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.SaleButton.onHoverState.BorderThickness = 1;
            this.SaleButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.SaleButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.SaleButton.onHoverState.IconLeftImage = null;
            this.SaleButton.onHoverState.IconRightImage = null;
            this.SaleButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.SaleButton.OnIdleState.BorderRadius = 15;
            this.SaleButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.SaleButton.OnIdleState.BorderThickness = 1;
            this.SaleButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.SaleButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.SaleButton.OnIdleState.IconLeftImage = null;
            this.SaleButton.OnIdleState.IconRightImage = null;
            this.SaleButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaleButton.OnPressedState.BorderRadius = 15;
            this.SaleButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaleButton.OnPressedState.BorderThickness = 1;
            this.SaleButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaleButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SaleButton.OnPressedState.IconLeftImage = null;
            this.SaleButton.OnPressedState.IconRightImage = null;
            this.SaleButton.Size = new System.Drawing.Size(182, 39);
            this.SaleButton.TabIndex = 0;
            this.SaleButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SaleButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SaleButton.TextMarginLeft = 0;
            this.SaleButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.SaleButton.UseDefaultRadiusAndThickness = true;
            this.SaleButton.Click += new System.EventHandler(this.SaleButton_Click);
            // 
            // DashboardButton
            // 
            this.DashboardButton.AllowAnimations = true;
            this.DashboardButton.AllowMouseEffects = true;
            this.DashboardButton.AllowToggling = false;
            this.DashboardButton.AnimationSpeed = 200;
            this.DashboardButton.AutoGenerateColors = false;
            this.DashboardButton.AutoRoundBorders = false;
            this.DashboardButton.AutoSizeLeftIcon = true;
            this.DashboardButton.AutoSizeRightIcon = true;
            this.DashboardButton.BackColor = System.Drawing.Color.Transparent;
            this.DashboardButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.DashboardButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DashboardButton.BackgroundImage")));
            this.DashboardButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.DashboardButton.ButtonText = "Dashboard";
            this.DashboardButton.ButtonTextMarginLeft = 0;
            this.DashboardButton.ColorContrastOnClick = 45;
            this.DashboardButton.ColorContrastOnHover = 45;
            this.DashboardButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.DashboardButton.CustomizableEdges = borderEdges7;
            this.DashboardButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DashboardButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DashboardButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DashboardButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.DashboardButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DashboardButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DashboardButton.IconMarginLeft = 11;
            this.DashboardButton.IconPadding = 10;
            this.DashboardButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DashboardButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DashboardButton.IconSize = 25;
            this.DashboardButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.DashboardButton.IdleBorderRadius = 15;
            this.DashboardButton.IdleBorderThickness = 1;
            this.DashboardButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.DashboardButton.IdleIconLeftImage = null;
            this.DashboardButton.IdleIconRightImage = null;
            this.DashboardButton.IndicateFocus = true;
            this.DashboardButton.Location = new System.Drawing.Point(21, 275);
            this.DashboardButton.Name = "DashboardButton";
            this.DashboardButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardButton.OnDisabledState.BorderRadius = 15;
            this.DashboardButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardButton.OnDisabledState.BorderThickness = 1;
            this.DashboardButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardButton.OnDisabledState.IconLeftImage = null;
            this.DashboardButton.OnDisabledState.IconRightImage = null;
            this.DashboardButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.DashboardButton.onHoverState.BorderRadius = 15;
            this.DashboardButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.DashboardButton.onHoverState.BorderThickness = 1;
            this.DashboardButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.DashboardButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.DashboardButton.onHoverState.IconLeftImage = null;
            this.DashboardButton.onHoverState.IconRightImage = null;
            this.DashboardButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.DashboardButton.OnIdleState.BorderRadius = 15;
            this.DashboardButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.DashboardButton.OnIdleState.BorderThickness = 1;
            this.DashboardButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.DashboardButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.DashboardButton.OnIdleState.IconLeftImage = null;
            this.DashboardButton.OnIdleState.IconRightImage = null;
            this.DashboardButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DashboardButton.OnPressedState.BorderRadius = 15;
            this.DashboardButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardButton.OnPressedState.BorderThickness = 1;
            this.DashboardButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DashboardButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.DashboardButton.OnPressedState.IconLeftImage = null;
            this.DashboardButton.OnPressedState.IconRightImage = null;
            this.DashboardButton.Size = new System.Drawing.Size(182, 39);
            this.DashboardButton.TabIndex = 0;
            this.DashboardButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.DashboardButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DashboardButton.TextMarginLeft = 0;
            this.DashboardButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.DashboardButton.UseDefaultRadiusAndThickness = true;
            this.DashboardButton.Click += new System.EventHandler(this.DashboardButton_Click);
            // 
            // MainForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1155, 800);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Inventory Management System";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton DashboardButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CustomersButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ProductsButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SaleButton;
        private Bunifu.UI.WinForms.BunifuPanel MainPanel;
        private Bunifu.UI.WinForms.BunifuImageButton CloseButton;
        private Bunifu.UI.WinForms.BunifuImageButton MinimizeAppButton;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton OrdersButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SaleLedgerButton;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton UsersButton;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
    }
}

